name: SentezOS CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-compile:
    name: SentezOS ISO Derleme
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Arch Linux Araclarini Kur
        run: pacman -Syu --noconfirm base-devel arch-install-scripts archiso

      - name: Ortami SentezOS Icin Hazirla
        run: |
          mkdir -p tmp-iso
          cp -r /usr/share/archiso/configs/releng/* tmp-iso/
          cp -rf iso-build/* tmp-iso/ || true

      - name: SentezOS ISO Imajini Uret
        run: mkarchiso -v -w /tmp/work -o out/ tmp-iso/

      - name: ISO Dosyasini Indirme Icin Hazirla
        uses: actions/upload-artifact@v4
        with:
          name: SentezOS-LiveCD
          path: out/*.iso
